### ISSUE TITLE
Codebase steward for community

### ISSUE THREAD

**Issue by MirjamvT** [t9tio/open-opportunities#17]
- Job title: Codebase steward for community
- Job link: https://about.publiccode.net/roles/community.html
- Organization: Foundation for Public Code
- Organization GitHub URL: https://publiccode.net/
- Locations of the job: Amsterdam
- Tech keywords of the job: Open Source

**Comment by timqian** [comment]
Thanks, will add it soon

**Comment by MirjamvT** [comment]
great, thanks!

**Comment by timqian** [comment]
The job is posted https://oo.t9t.io/jobs

**Comment by MirjamvT** [comment]
Thanks!
